package br.com.gmp.comps.keyboard;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.text.JTextComponent;

/**
 * Teclado virtual para campos de texto
 *
 * @author kaciano
 */
public class GMPKeyBoard extends JPanel {

    private JTextComponent textField;

    /**
     * Cria nova instancia de GMPKeyBoard
     */
    public GMPKeyBoard() {
        initialize();
    }

    /**
     * Cria nova instancia de GMPKeyBoard
     *
     * @param textField {@code JTextComponent} Campo de texto do teclado
     */
    public GMPKeyBoard(JTextComponent textField) {
        this.textField = textField;
        initialize();
    }

    /**
     * Inicializa o componente
     */
    private void initialize() {
        initComponents();
        addKeyListeners();
    }

    /**
     * Adiciona a funçao das teclas
     */
    private void addKeyListeners() {
        for (Component c : jPKeys.getComponents()) {
            if (c instanceof JButton) {
                final JButton button = (JButton) c;
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (textField != null) {
                            if (!jBUpperCase.isSelected()) {
                                textField.setText(textField.getText()
                                        + button.getText());
                            } else {
                                textField.setText(textField.getText()
                                        + button.getText().toUpperCase());
                            }
                        }
                    }
                });
            }
        }
    }

    /**
     * Funçao do backspace
     */
    private void backspace() {
        if (textField != null && textField.getText().length() > 0) {
            String text = textField.getText();
            textField.setText(text.substring(0, text.length() - 1));
        }
    }

    /**
     * Funçao da barra de espaço
     */
    private void space() {
        if (textField != null) {
            textField.setText(textField.getText() + " ");
        }
    }

    /**
     * Retorna o campo de texto do componente
     *
     * @return {@code JTextComponent} Campo de texto do teclado
     */
    public JTextComponent getTextField() {
        return textField;
    }

    /**
     * Modifica o campo de texto do componente
     *
     * @param textField {@code JTextComponent} Campo de texto do teclado
     */
    public void setTextField(JTextComponent textField) {
        this.textField = textField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPKeys = new javax.swing.JPanel();
        jBA = new javax.swing.JButton();
        jBB = new javax.swing.JButton();
        jBC = new javax.swing.JButton();
        jBD = new javax.swing.JButton();
        jBE = new javax.swing.JButton();
        jBF = new javax.swing.JButton();
        jBG = new javax.swing.JButton();
        jBH = new javax.swing.JButton();
        jBI = new javax.swing.JButton();
        jBJ = new javax.swing.JButton();
        jBK = new javax.swing.JButton();
        jBL = new javax.swing.JButton();
        jBM = new javax.swing.JButton();
        jBN = new javax.swing.JButton();
        jBO = new javax.swing.JButton();
        jBP = new javax.swing.JButton();
        jBQ = new javax.swing.JButton();
        jBR = new javax.swing.JButton();
        jBS = new javax.swing.JButton();
        jBT = new javax.swing.JButton();
        jBU = new javax.swing.JButton();
        jBV = new javax.swing.JButton();
        jBX = new javax.swing.JButton();
        jBW = new javax.swing.JButton();
        jBY = new javax.swing.JButton();
        jBZ = new javax.swing.JButton();
        jB0 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jPControls = new javax.swing.JPanel();
        jBBackSpace = new javax.swing.JButton();
        jBSpace = new javax.swing.JButton();
        jBUpperCase = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(575, 194));
        setMinimumSize(new java.awt.Dimension(575, 194));
        setPreferredSize(new java.awt.Dimension(575, 194));

        jPKeys.setMaximumSize(new java.awt.Dimension(500, 145));
        jPKeys.setMinimumSize(new java.awt.Dimension(500, 145));
        jPKeys.setPreferredSize(new java.awt.Dimension(500, 145));
        jPKeys.setLayout(new java.awt.GridLayout(3, 12));

        jBA.setText("a");
        jPKeys.add(jBA);

        jBB.setText("b");
        jPKeys.add(jBB);

        jBC.setText("c");
        jBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBC);

        jBD.setText("d");
        jBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBD);

        jBE.setText("e");
        jBE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBE);

        jBF.setText("f");
        jBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBF);

        jBG.setText("g");
        jBG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBG);

        jBH.setText("h");
        jBH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBH);

        jBI.setText("i");
        jBI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBI);

        jBJ.setText("j");
        jBJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBJ);

        jBK.setText("k");
        jBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBK);

        jBL.setText("l");
        jBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBL);

        jBM.setText("m");
        jBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBM);

        jBN.setText("n");
        jBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBN);

        jBO.setText("o");
        jBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBO);

        jBP.setText("p");
        jBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBP);

        jBQ.setText("q");
        jBQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBQ);

        jBR.setText("r");
        jBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBR);

        jBS.setText("s");
        jBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBS);

        jBT.setText("t");
        jBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBT);

        jBU.setText("u");
        jBU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBU);

        jBV.setText("v");
        jBV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBV);

        jBX.setText("x");
        jBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBX);

        jBW.setText("w");
        jBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBW);

        jBY.setText("y");
        jBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBY);

        jBZ.setText("z");
        jBZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jBZ);

        jB0.setText("0");
        jB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB0);

        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB1);

        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB2);

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB3);

        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB4);

        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB5);

        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB6);

        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB7);

        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB8);

        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAActionPerformed(evt);
            }
        });
        jPKeys.add(jB9);

        jBBackSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/direction/upLeft.png"))); // NOI18N
        jBBackSpace.setText("Backspace");
        jBBackSpace.setToolTipText("Backspace");
        jBBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackSpaceActionPerformed(evt);
            }
        });
        jPControls.add(jBBackSpace);

        jBSpace.setText("                                                           ");
        jBSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSpaceActionPerformed(evt);
            }
        });
        jPControls.add(jBSpace);

        jBUpperCase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/label/label.png"))); // NOI18N
        jBUpperCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBUpperCaseActionPerformed(evt);
            }
        });
        jPControls.add(jBUpperCase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPKeys, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPControls, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPKeys, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBUpperCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBUpperCaseActionPerformed

    }//GEN-LAST:event_jBUpperCaseActionPerformed

    private void jBSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSpaceActionPerformed
        space();
    }//GEN-LAST:event_jBSpaceActionPerformed

    private void jBBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackSpaceActionPerformed
        backspace();
    }//GEN-LAST:event_jBBackSpaceActionPerformed

    private void jBAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB0;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBA;
    private javax.swing.JButton jBB;
    private javax.swing.JButton jBBackSpace;
    private javax.swing.JButton jBC;
    private javax.swing.JButton jBD;
    private javax.swing.JButton jBE;
    private javax.swing.JButton jBF;
    private javax.swing.JButton jBG;
    private javax.swing.JButton jBH;
    private javax.swing.JButton jBI;
    private javax.swing.JButton jBJ;
    private javax.swing.JButton jBK;
    private javax.swing.JButton jBL;
    private javax.swing.JButton jBM;
    private javax.swing.JButton jBN;
    private javax.swing.JButton jBO;
    private javax.swing.JButton jBP;
    private javax.swing.JButton jBQ;
    private javax.swing.JButton jBR;
    private javax.swing.JButton jBS;
    private javax.swing.JButton jBSpace;
    private javax.swing.JButton jBT;
    private javax.swing.JButton jBU;
    private javax.swing.JToggleButton jBUpperCase;
    private javax.swing.JButton jBV;
    private javax.swing.JButton jBW;
    private javax.swing.JButton jBX;
    private javax.swing.JButton jBY;
    private javax.swing.JButton jBZ;
    private javax.swing.JPanel jPControls;
    private javax.swing.JPanel jPKeys;
    // End of variables declaration//GEN-END:variables
}
