package br.com.gmp.comps.keyboard;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.text.JTextComponent;

/**
 * Componente de teclado numerico
 *
 * @author kaciano
 * @version 1.0
 */
public class GMPNumericKeyBoard extends JPanel {

    private JTextComponent textField;

    /**
     * Cria nova instancia de GMPNumericKeyBoard
     */
    public GMPNumericKeyBoard() {
        initialize();
    }

    /**
     * Cria nova instancia de GMPNumericKeyBoard
     *
     * @param textField {@code JTextComponent} Campo de texto do teclado
     */
    public GMPNumericKeyBoard(JTextComponent textField) {
        this.textField = textField;
        initialize();
    }

    /**
     * Inicializa o componente
     */
    private void initialize() {
        initComponents();
        addListeners();
    }

    /**
     * Adiciona a funçao das teclas
     */
    private void addListeners() {
        for (Component c : getComponents()) {
            if (c instanceof JButton) {
                final JButton button = (JButton) c;
                button.addActionListener(new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (textField != null) {
                            textField.setText(textField.getText()
                                    + button.getText().toUpperCase());
                        }
                    }
                });
            }
        }
    }

    public JTextComponent getTextField() {
        return textField;
    }

    public void setTextField(JTextComponent textField) {
        this.textField = textField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonStar = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonHash = new javax.swing.JButton();
        jBBackspace = new javax.swing.JButton();
        jBSpace = new javax.swing.JButton();
        empty = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(5, 3));

        jButton1.setText("1");
        add(jButton1);

        jButton2.setText("2");
        add(jButton2);

        jButton3.setText("3");
        add(jButton3);

        jButton4.setText("4");
        add(jButton4);

        jButton5.setText("5");
        add(jButton5);

        jButton6.setText("6");
        add(jButton6);

        jButton7.setText("7");
        add(jButton7);

        jButton8.setText("8");
        add(jButton8);

        jButton9.setText("9");
        add(jButton9);

        jButtonStar.setText("*");
        add(jButtonStar);

        jButton0.setText("0");
        add(jButton0);

        jButtonHash.setText("#");
        add(jButtonHash);

        jBBackspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/direction/upLeft.png"))); // NOI18N
        jBBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBackspaceActionPerformed(evt);
            }
        });
        add(jBBackspace);

        jBSpace.setText("_");
        jBSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSpaceActionPerformed(evt);
            }
        });
        add(jBSpace);
        add(empty);
    }// </editor-fold>//GEN-END:initComponents

    private void jBBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBackspaceActionPerformed
        if (textField != null) {
            if (textField != null && textField.getText().length() > 0) {
                String text = textField.getText();
                textField.setText(text.substring(0, text.length() - 1));
            }
        }
    }//GEN-LAST:event_jBBackspaceActionPerformed

    private void jBSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSpaceActionPerformed
        if (textField != null) {
            textField.setText(textField.getText() + " ");
        }
    }//GEN-LAST:event_jBSpaceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel empty;
    private javax.swing.JButton jBBackspace;
    private javax.swing.JButton jBSpace;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonHash;
    private javax.swing.JButton jButtonStar;
    // End of variables declaration//GEN-END:variables
}
