package br.com.gmp.comps.togglebutton;

import br.com.gmp.comps.BaseColors;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.JToggleButton;
import javax.swing.border.LineBorder;

/**
 * GMPToggleButton
 *
 * @author kaciano
 */
public class GMPToggleButton extends JToggleButton {

    /**
     * Cria nova instancia de GMPToggleButton
     */
    public GMPToggleButton() {
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param text
     */
    public GMPToggleButton(String text) {
        super(text);
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param icon
     */
    public GMPToggleButton(Icon icon) {
        super(icon);
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param text
     * @param icon
     */
    public GMPToggleButton(String text, Icon icon) {
        super(text, icon);
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param text
     * @param selected
     */
    public GMPToggleButton(String text, boolean selected) {
        super(text, selected);
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param action
     */
    public GMPToggleButton(Action action) {
        super(action);
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param icon
     * @param selected
     */
    public GMPToggleButton(Icon icon, boolean selected) {
        super(icon, selected);
        initComponents();
        configurations();
    }

    /**
     * Cria nova instancia de GMPToggleButton
     *
     * @param text
     * @param icon
     * @param selected
     */
    public GMPToggleButton(String text, Icon icon, boolean selected) {
        super(text, icon, selected);
        initComponents();
        configurations();
    }

    /**
     * Efetua as modificações necessárias no componente
     */
    private void configurations() {
        setContentAreaFilled(false);
        setOpaque(false);
        setBorder(new LineBorder(Color.gray));
        setBorderPainted(false);
        this.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent ie) {
                if (isSelected()) {
                    setOpaque(true);
                    setBorderPainted(true);
                    setBackground(BaseColors.systemColor);
                } else {
                    setOpaque(false);
                    setBorderPainted(false);
                    setBackground(new JToggleButton().getBackground());
                }
            }
        });
        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent me) {
                setOpaque(true);
                setBorderPainted(true);
                setBackground(BaseColors.systemColor);
            }

            @Override
            public void mouseExited(MouseEvent me) {
                if (!isSelected()) {
                    setOpaque(false);
                    setBorderPainted(false);
                    setBackground(new JToggleButton().getBackground());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
