package br.com.gmp.comps.list;

import br.com.gmp.comps.model.GListModel;
import javax.swing.JList;

/**
 * Lista customizada
 *
 * @author kaciano
 * @version 1.0
 */
public class GList extends JList {

    private GListModel<?> model;

    /**
     * Cria nova instancia de GList
     */
    public GList() {
        this.model = new GListModel<>();
        initialize();
    }

    /**
     * Cria nova instancia de GList
     *
     * @param model <code>GListModel(?)</code> Modelo
     */
    public GList(GListModel<?> model) {
        this.model = model;
    }

    /**
     * Método de inicialização
     */
    private void initialize() {
        initComponents();
        setModel(model);
    }

    /**
     * Remove apenas os itens selecionados, caso não aja nenhum, dispara um
     * alerta
     */
    public void removeSelected() {
        if (getSelectedIndices() != null) {
            model.remove(getSelectedIndices());
        }
    }

    @Override
    public GListModel<?> getModel() {
        return model;
    }

    /**
     * Modifica o modelo de listas
     *
     * @param model <code>GListModel(?)</code> Modelo
     */
    public void setModel(GListModel<?> model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
