/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gmp.comps.player;

import javax.swing.JToolBar;

/**
 *
 * @author kaciano
 */
public class GPlayer extends JToolBar {

    /**
     * Creates new form GPlayer
     */
    public GPlayer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBPrevious = new javax.swing.JButton();
        jBPlay = new javax.swing.JButton();
        jBPause = new javax.swing.JButton();
        jBStop = new javax.swing.JButton();
        jBNext = new javax.swing.JButton();
        gTTrack = new br.com.gmp.comps.textfield.GTextField();

        setFloatable(false);
        setRollover(true);
        setMaximumSize(new java.awt.Dimension(32767, 23));
        setMinimumSize(new java.awt.Dimension(300, 23));
        setPreferredSize(new java.awt.Dimension(300, 23));

        jBPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/transition/begining.png"))); // NOI18N
        jBPrevious.setFocusable(false);
        jBPrevious.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPrevious.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jBPrevious);

        jBPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/multimedia/unpause.png"))); // NOI18N
        jBPlay.setFocusable(false);
        jBPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPlay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jBPlay);

        jBPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/multimedia/pause.png"))); // NOI18N
        jBPause.setFocusable(false);
        jBPause.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPause.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jBPause);

        jBStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/progress/stop.png"))); // NOI18N
        jBStop.setFocusable(false);
        jBStop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBStop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jBStop);

        jBNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ComponentIcons/transition/end.png"))); // NOI18N
        jBNext.setFocusable(false);
        jBNext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBNext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(jBNext);

        gTTrack.setEditable(false);
        gTTrack.setBackground(new java.awt.Color(0, 0, 0));
        gTTrack.setForeground(new java.awt.Color(13, 160, 1));
        gTTrack.setMaximumSize(new java.awt.Dimension(23768, 23));
        gTTrack.setMinimumSize(new java.awt.Dimension(200, 23));
        gTTrack.setPreferredSize(new java.awt.Dimension(150, 23));
        add(gTTrack);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.gmp.comps.textfield.GTextField gTTrack;
    private javax.swing.JButton jBNext;
    private javax.swing.JButton jBPause;
    private javax.swing.JButton jBPlay;
    private javax.swing.JButton jBPrevious;
    private javax.swing.JButton jBStop;
    // End of variables declaration//GEN-END:variables
}
