/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.gmp.comps;

import br.com.gmp.comps.cleaner.ComponentCleaner;

/**
 *
 * @author kaciano
 */
public class TestClean extends javax.swing.JFrame {

    /**
     * Creates new form TestClean
     */
    public TestClean() {
        initComponents();
        ComponentCleaner cc = new ComponentCleaner(false);
        cc.clean(jPRaiz);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPRaiz = new javax.swing.JPanel();
        jPSub1 = new javax.swing.JPanel();
        jPSub2 = new javax.swing.JPanel();
        jPSub3 = new javax.swing.JPanel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        gTextField3 = new br.com.gmp.comps.textfield.GTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        gTextField4 = new br.com.gmp.comps.textfield.GTextField();
        jCheckBox8 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        gTextField2 = new br.com.gmp.comps.textfield.GTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        numericTextField1 = new br.com.gmp.comps.textfield.numeric.NumericTextField();
        jTabbed1 = new javax.swing.JTabbedPane();
        jPTab1 = new javax.swing.JPanel();
        jPTab2 = new javax.swing.JPanel();
        gTextField1 = new br.com.gmp.comps.textfield.GTextField();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        gTextField5 = new br.com.gmp.comps.textfield.GTextField();
        jCheckBox10 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPRaiz.setBackground(new java.awt.Color(1, 1, 1));
        jPRaiz.setName("jPRaiz"); // NOI18N

        jPSub1.setBackground(new java.awt.Color(81, 81, 81));
        jPSub1.setName("jPSub1"); // NOI18N

        jPSub2.setBackground(new java.awt.Color(111, 111, 111));
        jPSub2.setName("jPSub2"); // NOI18N

        jPSub3.setBackground(new java.awt.Color(175, 175, 175));
        jPSub3.setForeground(new java.awt.Color(175, 175, 175));
        jPSub3.setName("jPSub3"); // NOI18N

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("jCheckBox5");
        jCheckBox5.setName("jCheckBox5"); // NOI18N

        jCheckBox6.setText("jCheckBox6");
        jCheckBox6.setName("jCheckBox6"); // NOI18N

        gTextField3.setText("gTextField2");
        gTextField3.setName("gTextField3"); // NOI18N
        gTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSub3Layout = new javax.swing.GroupLayout(jPSub3);
        jPSub3.setLayout(jPSub3Layout);
        jPSub3Layout.setHorizontalGroup(
            jPSub3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSub3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSub3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6)
                    .addComponent(gTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPSub3Layout.setVerticalGroup(
            jPSub3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSub3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox6)
                .addContainerGap())
        );

        jCheckBox7.setText("jCheckBox6");
        jCheckBox7.setName("jCheckBox7"); // NOI18N

        gTextField4.setText("gTextField2");
        gTextField4.setName("gTextField4"); // NOI18N
        gTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gTextField4ActionPerformed(evt);
            }
        });

        jCheckBox8.setSelected(true);
        jCheckBox8.setText("jCheckBox5");
        jCheckBox8.setName("jCheckBox8"); // NOI18N

        javax.swing.GroupLayout jPSub2Layout = new javax.swing.GroupLayout(jPSub2);
        jPSub2.setLayout(jPSub2Layout);
        jPSub2Layout.setHorizontalGroup(
            jPSub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSub2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPSub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox7)
                    .addComponent(gTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPSub2Layout.setVerticalGroup(
            jPSub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSub2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSub2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPSub2Layout.createSequentialGroup()
                        .addComponent(jCheckBox8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox7))
                    .addComponent(jPSub3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        gTextField2.setText("gTextField2");
        gTextField2.setName("gTextField2"); // NOI18N

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.setName("jCheckBox3"); // NOI18N

        jCheckBox4.setText("jCheckBox4");
        jCheckBox4.setName("jCheckBox4"); // NOI18N

        numericTextField1.setText("numericTextField1");
        numericTextField1.setName("numericTextField1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numericTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3)
                            .addComponent(gTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(numericTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(gTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout jPSub1Layout = new javax.swing.GroupLayout(jPSub1);
        jPSub1.setLayout(jPSub1Layout);
        jPSub1Layout.setHorizontalGroup(
            jPSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSub1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPSub1Layout.setVerticalGroup(
            jPSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSub1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPSub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbed1.setName("jTabbed1"); // NOI18N

        jPTab1.setName("jPTab1"); // NOI18N

        javax.swing.GroupLayout jPTab1Layout = new javax.swing.GroupLayout(jPTab1);
        jPTab1.setLayout(jPTab1Layout);
        jPTab1Layout.setHorizontalGroup(
            jPTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
        );
        jPTab1Layout.setVerticalGroup(
            jPTab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );

        jTabbed1.addTab("tab1", jPTab1);

        jPTab2.setName("jPTab2"); // NOI18N

        gTextField1.setText("gTextField1");
        gTextField1.setName("gTextField1"); // NOI18N

        jTextField1.setText("jTextField1");
        jTextField1.setName("jTextField1"); // NOI18N

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setName("jCheckBox2"); // NOI18N

        javax.swing.GroupLayout jPTab2Layout = new javax.swing.GroupLayout(jPTab2);
        jPTab2.setLayout(jPTab2Layout);
        jPTab2Layout.setHorizontalGroup(
            jPTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTab2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTab2Layout.createSequentialGroup()
                        .addComponent(gTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPTab2Layout.setVerticalGroup(
            jPTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTab2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPTab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbed1.addTab("tab2", jPTab2);

        jCheckBox9.setText("jCheckBox4");
        jCheckBox9.setName("jCheckBox9"); // NOI18N

        gTextField5.setText("gTextField2");
        gTextField5.setName("gTextField5"); // NOI18N

        jCheckBox10.setSelected(true);
        jCheckBox10.setText("jCheckBox3");
        jCheckBox10.setName("jCheckBox10"); // NOI18N

        javax.swing.GroupLayout jPRaizLayout = new javax.swing.GroupLayout(jPRaiz);
        jPRaiz.setLayout(jPRaizLayout);
        jPRaizLayout.setHorizontalGroup(
            jPRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRaizLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSub1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPRaizLayout.createSequentialGroup()
                        .addGroup(jPRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10)
                            .addComponent(gTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbed1)))
                .addContainerGap())
        );
        jPRaizLayout.setVerticalGroup(
            jPRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRaizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRaizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRaizLayout.createSequentialGroup()
                        .addComponent(gTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gTextField3ActionPerformed

    private void gTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestClean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestClean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestClean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestClean.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TestClean().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.gmp.comps.textfield.GTextField gTextField1;
    private br.com.gmp.comps.textfield.GTextField gTextField2;
    private br.com.gmp.comps.textfield.GTextField gTextField3;
    private br.com.gmp.comps.textfield.GTextField gTextField4;
    private br.com.gmp.comps.textfield.GTextField gTextField5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JPanel jPRaiz;
    private javax.swing.JPanel jPSub1;
    private javax.swing.JPanel jPSub2;
    private javax.swing.JPanel jPSub3;
    private javax.swing.JPanel jPTab1;
    private javax.swing.JPanel jPTab2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbed1;
    private javax.swing.JTextField jTextField1;
    private br.com.gmp.comps.textfield.numeric.NumericTextField numericTextField1;
    // End of variables declaration//GEN-END:variables
}
