package br.com.gmp.comps.separator;

import javax.swing.JSeparator;

/**
 *
 * @author kaciano
 */
public class GMPSeparator extends JSeparator {

    /**
     * Creates new form GMPSeparator
     */
    public GMPSeparator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
