package br.com.gmp.comps;

import br.com.gmp.comps.wizard.listener.WizardListener;
import br.com.gmp.comps.wizard.task.panel.WizardTaskPanel;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author kaciano
 */
public class WizardTest extends javax.swing.JFrame implements WizardListener {

    private List<WizardTaskPanel> taskList = new LinkedList<>();

    /**
     * Creates new form WizardTest
     */
    public WizardTest() {
        initComponents();
        taskList.add(wizardTaskPanel1);
        taskList.add(wizardTaskPanel2);
        wizard.setTaskList(taskList);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wizardTaskPanel1 = new br.com.gmp.comps.wizard.task.panel.WizardTaskPanel();
        jT1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        wizardTaskPanel2 = new br.com.gmp.comps.wizard.task.panel.WizardTaskPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        wizard = new br.com.gmp.comps.wizard.WizardPanel();

        wizardTaskPanel1.setCompleted(java.lang.Boolean.FALSE);
        wizardTaskPanel1.setDescription("Teste descrição dos infernos");
        wizardTaskPanel1.setTitle("Teste 1");

        jT1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        jTextField3.setText("jTextField1");

        jLabel3.setText("jLabel1");

        jTextField4.setText("jTextField1");

        jLabel4.setText("jLabel1");

        jButton1.setText("jButton1");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout wizardTaskPanel1Layout = new javax.swing.GroupLayout(wizardTaskPanel1);
        wizardTaskPanel1.setLayout(wizardTaskPanel1Layout);
        wizardTaskPanel1Layout.setHorizontalGroup(
            wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizardTaskPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(wizardTaskPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jT1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wizardTaskPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(wizardTaskPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        wizardTaskPanel1Layout.setVerticalGroup(
            wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizardTaskPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wizardTaskPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        wizardTaskPanel2.setDescription("Teste descrição dos infernos demoniacos");
        wizardTaskPanel2.setTitle("Teste 2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout wizardTaskPanel2Layout = new javax.swing.GroupLayout(wizardTaskPanel2);
        wizardTaskPanel2.setLayout(wizardTaskPanel2Layout);
        wizardTaskPanel2Layout.setHorizontalGroup(
            wizardTaskPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        wizardTaskPanel2Layout.setVerticalGroup(
            wizardTaskPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(wizard, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WizardTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private br.com.gmp.comps.wizard.WizardPanel wizard;
    private br.com.gmp.comps.wizard.task.panel.WizardTaskPanel wizardTaskPanel1;
    private br.com.gmp.comps.wizard.task.panel.WizardTaskPanel wizardTaskPanel2;
    // End of variables declaration//GEN-END:variables

    @Override
    public void previous() {
        System.out.println(this.getClass().getName() + " voltou!");
    }

    @Override
    public void next() {
        System.out.println(this.getClass().getName() + " avançou!");
    }

    @Override
    public void cancel() {
        System.out.println(this.getClass().getName() + " cancelou!");
    }

    @Override
    public void info() {
        System.out.println(this.getClass().getName() + " pediu informações!");
    }

    @Override
    public List<WizardTaskPanel> getTaskList() {
        return this.taskList;
    }
}
